sequenceDiagram
    actor A as Alice
    participant C as CTP
    participant D as Default Agent
    participant E as Edge Agent
    A->>C: POST request /admin/agentmanifest/create
    activate C
    Note right of A: agentGroup=Default<br>agentID=default#8200;
    C->>D: :createAgentManifest
    activate D
    C-->>A: response status code
    deactivate C
    D->>D: dfs.saveScaffolding
    D->>D: dfs.saveDefaultAgentManifest
    D->>E: dfs.saveEdgeAgentManifest
    deactivate D
    activate E
    E-->>C: :edgeServerPing
    deactivate E
