sequenceDiagram
    actor A as Alice
    participant C as CTP
    participant D as Default Agent
    participant E as Edge Agent
    A->>+C: /admin/agentmanifest/create
    Note over A,C: agentGroup=Default<br>agentID=default
    C->>D: :createAgentManifest
    activate D
    D->>D: saveScaffolding
    D->>D: saveDefaultAgentManifest
    D->>+E: saveEdgeAgentManifest
    deactivate D
    E-->>-C: edgeServerPing