flowchart LR
  subgraph P1[Pod]
    subgraph C1[Container]
      subgraph B1[App]
        I1(SLF4J) --> |Logback| A1(FluentAppender)
      end
      A1 --> |logging<br/>audit<br/>metrics<br/>tracing| F1(fluentbit)
    end
    subgraph C2[Container]
      subgraph B2[App]
        I2(SLF4J) --> |Logback| A2(FluentAppender)
      end
      A2 --> |logging<br/>audit<br/>metrics<br/>tracing| F2(fluentbit)
    end
    subgraph C3[Container]
      subgraph B3[App]
        I3(SLF4J) --> |Logback| A3(FluentAppender)
      end
      A3 --> |logging<br/>audit<br/>metrics<br/>tracing| F3(fluentbit)
    end
  end
  F1 --> L(((fluentd)))
  F2 --> L
  F3 --> L
  L --> E1[(OpenSearch)]
  L --> E2[(Cassandra)]
  subgraph P3[Pod]
    subgraph C4[Container]
      K1(Kibana)
      K2(Grafana)
    end
  end
  E1 -.- K1
  E2 -.- K2
