flowchart LR
  subgraph N1[Node]
    subgraph C11[Container]
      subgraph B1[App]
        I1(Log4J2 API) --> A1(FluentAppender)
      end
    end
    subgraph C12[Container]
      A1 --> |journal<br/>audit<br/>metrics<br/>tracing| F1(fluentbit)
    end
  end
  subgraph N2[Node]
    subgraph C21[Container]
      subgraph B2[App]
        I2(Log4J2 API) --> A2(FluentAppender)
      end
    end
    subgraph C22[Container]
      A2 --> |journal<br/>audit<br/>metrics<br/>tracing| F2(fluentbit)
    end
  end
  subgraph N3[Node]
    subgraph C31[Container]
      subgraph B3[App]
        I3(Log4J2 API) --> A3(FluentAppender)
      end
    end
    subgraph C32[Container]
      A3 --> |journal<br/>audit<br/>metrics<br/>tracing| F3(fluentbit)
    end
  end
  F1 --> L1((("fluentd<br/>(active)")))
  F2 --> L1
  F3 --> L1
  L1 --> E1[(Cassandra)]
  L1 --> E2[(OpenSearch)]
  F1 -.-> L2((("fluentd<br/>(backup)")))
  F2 -.-> L2
  F3 -.-> L2
  L2 -.-> E1
  L2 -.-> E2
  subgraph P4[Pod]
    subgraph C4[Container]
      K4(Grafana)
    end
  end
  subgraph P5[Pod]
    subgraph C5[Container]
      K5(Kibana)
    end
  end
  subgraph P6[Pod]
    subgraph C6[Container]
      K6(Gainsight)
    end
  end
  E1 -.- K4
  E2 -.- K5
  E2 -.- K6
