flowchart LR
  subgraph P1[Pod]
    subgraph C11[Container]
      subgraph B1[App]
        I1(Log4J2 API) --> A1(FluentAppender)
      end
    end
    subgraph C12[Container]
      A1 --> |journal<br/>audit<br/>metrics<br/>tracing| F1(fluentbit)
    end
  end
  subgraph P2[Pod]
    subgraph C21[Container]
      subgraph B2[App]
        I2(Log4J2 API) --> A2(FluentAppender)
      end
    end
    subgraph C22[Container]
      A2 --> |journal<br/>audit<br/>metrics<br/>tracing| F2(fluentbit)
    end
  end
  subgraph P3[Pod]
    subgraph C31[Container]
      subgraph B3[App]
        I3(Log4J2 API) --> A3(FluentAppender)
      end
    end
    subgraph C32[Container]
      A3 --> |journal<br/>audit<br/>metrics<br/>tracing| F3(fluentbit)
    end
  end
  F1 --> L(((fluentd)))
  F2 --> L
  F3 --> L
  L --> E1[(OpenSearch)]
  L --> E2[(Cassandra)]
  subgraph P4[Pod]
    subgraph C4[Container]
      K4(Kibana)
    end
  end
  subgraph P5[Pod]
    subgraph C5[Container]
      K5(Grafana)
    end
  end
  E1 -.- K4
  E2 -.- K5
