---
config:
  sankey:
    width: 900
    height: 900
    showValues: false
---
sankey-beta
Functional services,Packages,6
Packages,WmPublic,2
WmPublic,webM Public services,2
Packages,WmSample,2
WmSample,webM Sample services,2

Layered Products,"$type",2
"$type","webM $type Product",2
Connectors,"$protocol",2
"$protocol","webM $protocol Connector",2
Enterprise services,Layered Products,2
Enterprise services,Adapters,9
Adapters,JDBC,4
JDBC,Amazon RDS,2
JDBC,Amazon Aurora,2
Adapters,FlatFile,1
FlatFile,Amazon S3,1
Adapters,Parquet,1
Parquet,Amazon S3,1
Enterprise services,Connectors,2
Enterprise services,Standards,9
Standards,XML,0.5
XML,Amazon Web services,0.5
Standards,OData,0.5
OData,Amazon Web services,0.5
Standards,gRPC,0.5
gRPC,Amazon Web services,0.5
Standards,graphQL,0.5
graphQL,Amazon Web services,0.5
Standards,HTTP,0.5
HTTP,Amazon Web services,0.5
Standards,FTP,0.5
FTP,Amazon Web services,0.5
Standards,E-Mail,0.5
E-Mail,Amazon Web services,0.5
Standards,JSON,1
JSON,Amazon Web services,0.5
JSON,RESTful APIs,0.5
RESTful APIs,Amazon API Gateway,1
Standards,OpenAPI,1
OpenAPI,RESTful APIs,0.5
OpenAPI,WebSocket APIs,0.5
Standards,Websocket,0.5
Websocket,WebSocket APIs,0.5
WebSocket APIs,Amazon API Gateway,1

Infrastructure services,Messaging,4
Messaging,Message Pub & Sub,2
Message Pub & Sub,Amazon SNS,2
Messaging,Message Queueing,2
Message Queueing,Amazon SQS,2
Infrastructure services,Pooling,2
Pooling,Amazon EC2,2
Infrastructure services,Authentication,0.66
Authentication,Security Identity & Compliance,0.66
Infrastructure services,Authorization,0.66
Authorization,Security Identity & Compliance,0.66
Infrastructure services,Licensing,0.66
Licensing,Security Identity & Compliance,0.66
Security Identity & Compliance,Amazon Cognito,2
Infrastructure services,Statistics,2
Statistics,AWS X-Ray,2
Infrastructure services,Logging,1
Logging,Amazon CloudWatch,1
Infrastructure services,Metering,1
Metering,Amazon CloudWatch,1
Infrastructure services,Auditing,2
Auditing,AWS CloudTrail,2
Infrastructure services,Caching,2
Caching,Amazon ElastiCache,2
Infrastructure services,Cluster,2
Cluster,AWS Elastic Load Balancing,2
Infrastructure services,Scheduler,2
Scheduler,Amazon EventBridge,2

Application services,Orchestration,2
Orchestration,Flow Engine,2
Flow Engine,AWS Step Functions,2
Application services,Management,4
Management,Configurations,2
Management,Admin API,2
Admin API,AWS Management Console,2
Configurations,AWS Config,2
Application services,Deployment,2
Deployment,Package Manager,0.66
Package Manager,AWS CodeDeploy,0.66
Deployment,Deployer API,0.66
Deployer API,AWS CodeDeploy,0.66
Deployment,Platform Manager (SPM),0.66
Platform Manager (SPM),AWS CodeDeploy,0.66
Application services,Design,2
Design,Designer API,2
Designer API,AWS Step Functions Workflow Studio,2
