---
config:
  sankey:
    width: 800
    height: 800
    showValues: false
---
sankey-beta

Adapters,Functional services,4
Connectors,Functional services,4
API Gateway,Functional services,4
Layered Products,Functional services,4
HTTP,Enterprise services,2
E-Mail,Enterprise services,2
FTP,Enterprise services,2
Flatfile,Enterprise services,2
Websocket,Enterprise services,2
Scheduler,Enterprise services,2
OData,Standards,2
JSON,Standards,2
XML,Standards,2
gRPC,Standards,2
graphQL,Standards,2
OpenAPI,Standards,2
Parquet,Standards,2
Standards,Enterprise services,14
Flow Engine,Application services,2
wpm,Application services,2
Package Manager,Application services,2
Passman,Application services,2
Messaging,Application services,2
Webservices,Application services,2
Designer API,Application services,2
Admin API,Application services,2
Deployer API,Application services,2
Platform Manager (SPM),Application services,2
Configurations,Application services,2
Pooling,Infrastructure services,2
Authentication,Infrastructure services,2
Authorization,Infrastructure services,2
Licensing,Infrastructure services,2
Statistics,Infrastructure services,2
Logging,Infrastructure services,2
Auditing,Infrastructure services,2
Metering,Infrastructure services,2
Caching,Infrastructure services,2
Cluster,Infrastructure services,2
