flowchart BT
  subgraph hub[Hub]
    subgraph hub.git["Git"]
      subgraph hub.git.project["Project"]
        hub.git.wf["Workflow"]
        hub.git.sd(["Scaffold"])
        hub.git.am(["Agent Manifest"])
      end
      subgraph hub.git.pkg["Package"]
        hub.git.pkg.pkg["Package"]
      end
    end
    subgraph hub.svc["Service Runtime"]
      hub.svc.scaffold(["Scaffold"])
      hub.svc.agent(["Dev Agent"])
      hub.svc.pkg["Package"]
    end
  end
  subgraph spoke [Spoke]
    subgraph spoke.svc["Service Runtime"]
      spoke.svc.agent(["Test Agent"])
      spoke.svc.pkg["Package"]
    end
  end
  hub.svc -- push scaffold --> hub.git.sd
  hub.svc -- push manifest --> hub.git.am
  hub.svc -- push package ---> hub.git.pkg.pkg
  spoke.svc -- pull manifest ---> hub.svc
  spoke.svc -- pull package --> hub.svc & hub.git.pkg.pkg
